[package]
name = "aoc24"
version = "0.0.1"
edition = "2021"

[dependencies]
aoclib-rs = { git = "https://github.com/glennhartmann/aoclib-rs.git", tag = "v0.0.1" }

clap = { version = "4.5.20", features = ["derive"] }
once_cell = "1.20.2"
regex = "1.11.1"
